-------------Query 1 --------------------------
select PRODUCT.PRODUCTNAME,COUNT(PURCHASE.PRODUCTID) AS COUNTER 
FROM PURCHASE INNER JOIN PRODUCT ON
PURCHASE.PRODUCTID = PRODUCT.PRODUCTID 
group by PURCHASE.PRODUCTID, PRODUCT.PRODUCTNAME 
HAVING  COUNT(PURCHASE.PRODUCTID) >= ALL(select COUNT(PURCHASE.PRODUCTID) FROM PURCHASE group by PURCHASE.PRODUCTID)

-------------Query 2 --------------------------
select Distinct product.PRODUCTNAME 
from PRODUCT left join purchase on
product.productid = purchase.productid 
where PRODUCT.PRODUCTID  
not in (select purchase.PRODUCTID from purchase where month(PURCHASE.TDATE) = 6 and year(PURCHASE.TDATE) = year(GETDATE()))

-------------Query 3 --------------------------
select distinct CUSTOMER.CUSTOMERNAME 
from CUSTOMER left join purchase 
on CUSTOMER.CUSTOMERNAME = purchase.CUSTOMERNAME 
where CUSTOMER.CUSTOMERNAME  
not in (select purchase.CUSTOMERNAME from purchase where year(PURCHASE.TDATE) = year(GETDATE()) - 1)

-------------Query 4 --------------------------
SELECT TOP 1 CUSTOMERNAME, COUNT(CUSTOMERNAME) 
AS HIGHESTPURCHASE FROM PURCHASE WHERE YEAR(TDATE) * 12 + MONTH(TDATE) = YEAR(GETDATE()) * 12 + MONTH(GETDATE()) 
GROUP BY CUSTOMERNAME ORDER BY HIGHESTPURCHASE desc

-------------Query 5 --------------------------
SELECT distinct CATEGORYNAME From PRODUCT, CATEGORY 
where CATEGORY.CATEGORYID = (select PRODUCT.CATEGORYID 
from PRODUCT where PRODUCT.PRODUCTID = ( SELECT max(PURCHASE.PRODUCTID) FROM PURCHASE ))

-------------Query 6 --------------------------
select PRODUCTNAME, (PRODUCT.PRODUCTID) ,CATEGORYID,PRODUCTPRICE,QUANTITY,COUNT(PURCHASE.PRODUCTID) 
AS Byers from CUSTOMER , PURCHASE, PRODUCT 
where CUSTOMER.CUSTOMERNAME = PURCHASE.CUSTOMERNAME and PURCHASE.PRODUCTID = PRODUCT.PRODUCTID 
group by PRODUCT.PRODUCTID,CATEGORYID,PRODUCTPRICE,QUANTITY,PRODUCTNAME 

